/**
 * AVEKSHA NETRA — AI Pipeline API Module
 */

import { apiClient, getStreamUrl } from "./client";

export const aiApi = {
  /**
   * Start AI YOLO detection worker for camera
   */
  startAi: (cameraId) => apiClient.post(`/api/cameras/${cameraId}/ai/start`),

  /**
   * Stop AI worker for camera
   */
  stopAi: (cameraId) => apiClient.post(`/api/cameras/${cameraId}/ai/stop`),

  /**
   * Get AI telemetry & frame processing status for camera
   */
  getCameraStatus: (cameraId) =>
    apiClient.get(`/api/cameras/${cameraId}/ai/status`),

  /**
   * Get status of all active camera workers
   */
  getAllStatus: () => apiClient.get("/api/ai/status"),

  /**
   * Get recent detection events generated by camera AI worker
   */
  getCameraEvents: (cameraId) =>
    apiClient.get(`/api/cameras/${cameraId}/events`),

  /**
   * Get active tracked entities for camera
   */
  getCameraTracks: (cameraId) =>
    apiClient.get(`/api/cameras/${cameraId}/tracks`),

  /**
   * Direct MJPEG AI stream URL
   */
  getAiStreamUrl: (cameraId) =>
    getStreamUrl(`/api/cameras/${cameraId}/ai-stream`),
};

export default aiApi;
